server:
  port: 18080
spring:
  application:
    name: yzunlp-qzfeng-service
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://${yzunlp.database.host}:${yzunlp.database.port}/${yzunlp.database.schema}?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${yzunlp.database.username}
    password: ${yzunlp.database.password}

mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

yzunlp:
  jwt:
    # 设置jwt签名加密时使用的秘钥   HMAC-SHA算法32字节
    user-secret-key: hjfAndHuang
    # 设置jwt过期时间 2小时
    user-ttl: 7200000
    # 设置前端传递过来的令牌名称
    user-token-name: token