yzu-nlp:
  database:
    host: 172.25.220.177
    port: 13306
    username: root
    password: admin
    schema: Questionnaire
  upload:
    user-upload-path: D:\\develop_cocos\\
    # D:\\develop_cocos\\
    # D:\\Code\\QzFeng\\src\\main\\resources\\uploads\\